### ISSUE TITLE
npx microbundle create myLib

### ISSUE THREAD

**Issue by devinrhode2** [developit/microbundle#1010]
Would love to have this tsdx [feature](https://github.com/jaredpalmer/tsdx#quick-start):
```
npx tsdx create mylib
```

This may be a starting point: https://github.com/gribnoysup/create-microbundle-module#whats-in-the-package

**Comment by devinrhode2** [comment]
For now, I'll bootstrap with tsdx, and maybe use microbundle if needed

**Comment by rschristian** [comment]
I think it's best to leave opinionated dev environments to users to configure and create. `tsdx` has a way bigger scope, as it specifically aims to help with things like Jest, TS, ESLint, and VSCode, which is why it supplies that creation tool. However, none of those tools fall into Microbundle's scope.

The only things a `create-microbundle` package would do is create a directory, install `microbundle` into it, and maybe copy a "kitchen sink" `package.json` config. This replaces a handful of shell commands, but would be much, much slower thanks to `npx` and network calls.

What you can do, and what I'd suggest, is to create a template repository on GitHub for yourself. You can create other repos from that template, allowing you to easily set a standardized config without needing to publish a package (and take up another package name).

**Comment by rschristian** [comment]
Closing this out as I don't think it's likely to become a first-party feature. Happy to see if anyone in the community creates a configuration though!

**Comment by devinrhode2** [comment]
Yeah I think your idea of creating a template is 100% the way to go
