### ISSUE TITLE
[Question] Is it possible to add or keep comments at the top of generated files?

### ISSUE THREAD

**Issue by szimek** [developit/microbundle#104]
I'd like to add or keep a copyright info at the top of generated files. Is it currently possible?

**Comment by Andarist** [comment]
It's not currently supported - you'd have to just concat generated files with your comments as postbuild step. I don't think it's something that we want to support at the moment - bigger fishes to fry. If you feel like contributing though we'd probably merge in a PR for this, you'd have to figure out an universal convention on what comments should get preserved - something like `@preserve` in the comment or something.

Closing this issue for now, but as mentioned - feel free to create a PR for this and if you let's discuss about specifics in its thread.

**Comment by rzoller** [comment]
It looks like preserving comments is quite easy, terser already has an option for that which by default preserves `@preserve` and `@license`, you can test it like this:

```
npx microbundle --no-compress
npx terser --compress --mangle --comments -- dist/bundle.js
```

However, if the use case of preserving comments is to include license information at the start of the bundle, this unfortunately doesn't work, because AFAIK there is no guarantee on the order of code in the bundle, i.e. just because the license comment appears at the top of the source entry point file, it doesn't mean that it will end up at the top of the bundled output.

To solve this problem, rollup has a concept of "banner" and "footer" for content to be added at the start/end of the bundle: https://github.com/rollup/rollup/issues/490
I guess this would be quite easy to add to microbundle, but would require "banner" and "footer" configuration options to be added to the CLI. Since my understanding is that microbundle tries to keep things simple, I don't know if it is desirable to do that.

**Comment by xavierfoucrier** [comment]
Related issue: https://github.com/developit/microbundle/issues/116
