### ISSUE TITLE
use --external for a list of specific dependencies

### ISSUE THREAD

**Issue by fantasia949** [developit/microbundle#106]
Currently, it seems "all" is the only value to be processed.
When I try to pass parameters to the CLI like `--external classnames,unistore`, `--external classnames, unistore`,  or `--external unistore`,  the output is not changed in either cases.

**Comment by Andarist** [comment]
Thanks for the report, gonna investigate this asap.

**Comment by Andarist** [comment]
It seems that this is not supported (yet). Going to implement it this week, thanks for bringing up the issue.

**Comment by jml6m** [comment]
I'm using v0.9.0 and `--external` still doesn't change the output for me. I'm trying to get rid of the `require()` statements in my compiled .mjs file because when I import it using the <script> tag in the browser I still get: `ReferenceError: require is not defined`

Because there are still require calls within the bundled code
