### ISSUE TITLE
Production bundle

### ISSUE THREAD

**Issue by porfirioribeiro** [developit/microbundle#115]
Hi, would it be possible to add an option to use https://github.com/rollup/rollup-plugin-replace
To be able to make different builds for development and production

**Comment by Andarist** [comment]
Sure thing, but could you specify for which format u'd like to output those 2 builds? Seems only relevant for umd (and maybe cjs targeting node).

**Comment by porfirioribeiro** [comment]
Well my idea is to make my library provide both production and development builds
```javascript
if (process.env.NODE_ENV === 'production') {
  module.exports = require('./cjs/react.production.min.js');
} else {
  module.exports = require('./cjs/react.development.js');
}
```

So i can add useful debug code for development but also provide the smallest code in production

**Comment by Andarist** [comment]
is your library targeting node, browsers or both?

**Comment by Andarist** [comment]
For browsers u dont need this. Just use `process.env.NODE_ENV` checks, do not replace them before publishing and let consumers' bundlers do that. 

Example in the wild can be check [here](https://github.com/final-form/react-final-form/blob/37a5827e91fb7b9e4db881371af8cc0ba980295d/src/Field.js#L108).

**Comment by porfirioribeiro** [comment]
Ok, i get it, will use that for now!

**Comment by stereobooster** [comment]
The same https://github.com/developit/microbundle/issues/181 ?

**Comment by FredyC** [comment]
Just referencing one issue we got reported over at mobx: https://github.com/mobxjs/mobx-react/issues/801

@Andarist I tend to agree that this should be indeed a concern for consumer bundlers. What about UMD? There is no bundling happening, it's used directly and it's unlikely user will be mocking `process` out.

Furthermore, when I look for inspiration to React package, they indeed are keeping env checks in development bundles, but removing (evaluating) them for a production bundle:

https://unpkg.com/browse/react@16.12.0/cjs/react.development.js
https://unpkg.com/browse/react@16.12.0/cjs/react.production.min.js

The TSDX went a slightly different route, they are keeping ESM bundle with those checks because it's a good assumption that one will be bundled. But CJS and UMD are stripped down. Have a look at Formik for example.

https://unpkg.com/browse/formik@2.0.4/dist/

**Comment by Andarist** [comment]
> What about UMD? 

Definitely should be replaced, UMDs are intended to be used "as is".

> Furthermore, when I look for inspiration to React package, they indeed are keeping env checks in development bundles, but removing (evaluating) them for a production bundle:

Keep in mind that actually this is React's entry point - https://unpkg.com/react@16.12.0/index.js . This is a proxy file to prod/dev bundles (similar strategy is used by https://preconstruct.tools/ ). It's written like this because process.env is supposedly slow in node, so better to just read it one time rather than all over the place. Also that dev bundle has actually replaced all `process.env.NODE_ENV` with `"development"` - it just wraps its content with one more non-replaced env check. Not sure why this would be needed? Maybe just some extra measure to be sure that nobody ships/executes two copies of React.

I believe a similar strategy (proxy file) could be used for CJS entries in microbundle

**Comment by FredyC** [comment]
Yea, so ultimately I believe the TSDX has chosen the right path and it would be nice if microbundle could follow :)

**Comment by AdrianMrn** [comment]
Heya, I'm getting this in a UMD build, any idea what the fix was @developit ?

**Comment by developit** [comment]
I don't recall. If you're trying to use env checks in UMD that's not recommended. If you're trying to use the React package and seeing this in bundles, try passing `--define process.env.NODE_ENV=production`

**Comment by AdrianMrn** [comment]
Thanks, `--define process.env.NODE_ENV=production` fixed it!
