### ISSUE TITLE
export in sub-folders?

### ISSUE THREAD

**Issue by FezVrasta** [developit/microbundle#260]
If I try to define the package.json as follows, it still outputs all the files in the same directory.

```
"main": "dist/cjs/index.js",
"umd:main": "dist/umd/index.js",
"module": "dist/es/index.js"
```

Is there any way to have the output files in different sub-folders?

**Comment by developit** [comment]
I think right now the only way would be to run `microbundle` 3 times:

```js
microbundle -f cjs -o dist/cjs
microbundle -f umd -o dist/umd
microbundle -f es -o dist/es
```

Another option might just be to `mv` the files after build.

Just curious - can you explain a bit about why you need the folders?  I'm hoping to change the output directory structure of Microbundle so that it's easier to do things like multiple entries in a single compile, and nested `package.json` directories.

**Comment by FezVrasta** [comment]
I use flow-copy-source to copy stuff into the cjs/ folder. I don't like to have the flow files together with all the bundles. It's confusing

**Comment by developit** [comment]
Duplicate of #157.
