### ISSUE TITLE
Glslify

### ISSUE THREAD

**Issue by dy** [developit/microbundle#275]
@developit what is the best way to organize [glslify](https://github.com/glslify) loading?
There are webpack loader, browserify transform, require replacer, babel and rollup plugins. Can we use any of them for that?

**Comment by developit** [comment]
Interesting question! I've not really used glslify so I'm not the most knowledgeable on this. Seems like it'd be tricky to come up with a generic solution though.  Since microbundle is based on Rollup, the rollup plugin would be the easiest path, but we don't have a way to inject rollup plugins since it would expose microbundle internals and break encapsulation.  That said, if everyone basically uses the same plugin, we have precedent for baking it into microbundle itself (like we did with typescript and css).

**Comment by dy** [comment]
@developit that's what parceljs does https://github.com/parcel-bundler/parcel/issues/2419
That would help so much developing webgl/regl components.
