### ISSUE TITLE
new.target is broken

### ISSUE THREAD

**Issue by adriengibrat** [developit/microbundle#285]
Using `tsconfigOverride` of [rollup-plugin-typescript2](https://github.com/ezolenko/rollup-plugin-typescript2/) to force `typescript compilerOptions.target` to `esnext` should be documented as it will override user configuration.

It introduce some strange behaviour in one of my [lib](https://github.com/adriengibrat/ts-custom-error) because I used typescript to transpile `new.target` in ES5 & it seems [babel does not](https://github.com/babel/babel/issues/1088) by default.

This behaviour was introduced in [0.8.0](https://github.com/developit/microbundle/releases/tag/0.8.0) see cebff34d415b00d424876f25f1a700fd4b17e21c.

Workaround: downgrade microbundle to version [0.7.0](https://github.com/developit/microbundle/releases/tag/0.7.0)

Using [babel-plugin-transform-new-target](https://babeljs.io/docs/en/babel-plugin-transform-new-target) with .babelrc `{  "plugins": ["@babel/plugin-transform-new-target"] }` is not an option until #25 is resolved.

**Comment by marvinhagemeister** [comment]
The current processing pipeline is `TypeScript -> babel -> rollup`, reason being that babel's transpiled output is smaller in some cases. Only having to deal with one compile greatly reduces maintenance burden for us and that's why the override is correct.

Allow custom user configuration either via `.babelrc` is on the radar, but nobody has taken up the effort yet. The best option for now would be to simply add the missing babel plugin.

@adriengibrat Can you make a PR that adds the missing babel plugin? I'd be happy to merge it.
