### ISSUE TITLE
exports is not defined when building for web browser

### ISSUE THREAD

**Issue by gweltaz-calori** [developit/microbundle#334]
After building for browser I get this message 

```
exports is not defined
```

I looked up through the code and it seems like the export object is missing.

You can try it at this repo [https://github.com/gweltaz-calori/plume](https://github.com/gweltaz-calori/plume) by doing `npm run build`

**Comment by developit** [comment]
Hi @gweltaz-calori. Microbundle produces 3 script variants by default, and you're loading the [CommonJS](https://blog.risingstack.com/node-js-at-scale-module-system-commonjs-require/) one, which is specific to Node.js.

This can be fixed by changing your package.json to point to the correct output:

```diff
{
  "name": "plume",
  "version": "1.0.0",
  "description": "",
-  "main": "src/index.js",
+  "main": "dist/plume.js",
+  "module": "dist/plume.mjs",
+  "browser": "dist/plume.umd.js",
+  "source": "src/index.js",
  "directories": {},
  "scripts": {
-    "build": "microbundle -i ./src/index.js -o ./dist --sourcemap false"
+    "build": "microbundle --sourcemap false"
  },
  "keywords": [],
  "author": "Gweltaz Calori",
  "license": "ISC",
  "devDependencies": {
    "microbundle": "^0.9.0"
  },
  "dependencies": {}
}
```

Notice that, with this approach, no options are required for microbundle.

Those fields can be tricky, here's what they mean:

```
"main": used for Node.js
"module": used for webpack 4+
"browser": used for webpack and unpkg.com
"source": used by microbundle
```
