### ISSUE TITLE
Invalid hook call. Hooks can only be called inside of the body of a function component

### ISSUE THREAD

**Issue by pBread** [developit/microbundle#537]
I receive the error `Invalid hook call. Hooks can only be called inside of the body of a function component` when attempting to use my Microbundled module in Create-React-App. Essentially, there are two versions of React. See [Dan's comment](https://github.com/facebook/react/issues/15315#issuecomment-479802153).

I ran into this issue previously but was able to solve it by adding ` --globals react=react1`, which felt like a hacky solution. However, I just re-ran `yarn install` and the issue came back.

Is there a known solution here?

Here's my module's package.json file.

```
{
  "dependencies": {
    "nanoid": "^2.1.8",
    "normalizr": "^3.4.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-redux": "^7.1.3",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "styled": "^1.0.0"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.3",
    "eslint": "^6.8.0",
    "eslint-plugin-react": "^7.17.0",
    "eslint-plugin-react-hooks": "^1.7.0",
    "prop-types": "^15.7.2"
  },
  "license": "UNLICENSED",
  "main": "dist/index.js",
  "module": "dist/index.es.js",
  "name": "tk-ux",
  "peerDependencies": {
    "prop-types": "^15.7.2"
  },
  "repository": "github:pBread/tk-ux.git",
  "scripts": {
    "build": "microbundle build   --alias API=src/Modules/API/index.js,Constants=src/Constants/index.js,Containers=src/Containers/index.js,Modules=src/Modules/index.js,Utilities=src/Utilities/index.js    --globals react=React     --jsx React.createElement",
    "dev": "yarn link && cd example && yarn link 'tk-ux' && yarn start",
    "serve": "microbundle watch   --alias API=src/Modules/API/index.js,Constants=src/Constants/index.js,Containers=src/Containers/index.js,Modules=src/Modules/index.js,Utilities=src/Utilities/index.js    --globals react=React     --jsx React.createElement"
  },
  "source": "./src/index.js",
  "umd:main": "dist/index.umd.js",
  "version": "1.0.0"
}
```

**Comment by pBread** [comment]
This may be related to `yarn link` behavior. I was able to resolve the issue (at least temporarily) by unlinking the package in my local environment then re-linking them.

I think this is still an issue that needs some clarification and/or documentation. Can anyone elaborate on best-practices for avoiding conflicts like these? i.e. accidentally creating two versions of a dependency.

**Comment by ForsakenHarmony** [comment]
try having `react` as a peer dependency

**Comment by pBread** [comment]
I think it was a combination of `--globals react=React,react-dom=ReactDOM` and adding them as peer dependencies. Although, I'm not sure if that was the full fix.

```json
{
  "dependencies": {
    "nanoid": "^2.1.8",
    "normalizr": "^3.4.1",
    "prop-types": "^15.7.2",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "eslint": "^6.8.0",
    "eslint-plugin-react": "^7.17.0",
    "eslint-plugin-react-hooks": "^2.3.0",
    "microbundle": "^0.11.0",
    "prop-types": "^15.7.2"
  },
  "files": ["dist"],
  "license": "UNLICENSED",
  "main": "dist/index.js",
  "module": "dist/index.es.js",
  "name": "tk-ux",
  "peerDependencies": {
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-redux": "^7.1.3"
  },
  "repository": "github:pBread/tk-ux.git",
  "scripts": {
    "build": "microbundle build     --globals react=React,react-dom=ReactDOM    --jsx React.createElement",
    "dev": "yarn dev:link && cd example && yarn start",
    "dev:link": "yarn link && cd example && yarn link 'tk-ux'",
    "dev:unlink": "yarn unlink",
    "serve": "yarn build --w"
  },
  "source": "./src/index.js",
  "unpkg": "dist/index.umd.js",
  "version": "1.0.0"
}
```

**Comment by ForsakenHarmony** [comment]
can you try without the `--globals ...`?

**Comment by ForsakenHarmony** [comment]
It's a bit weird, anything in `dependencies` and `peerDependencies` should automatically be treated as external (and not be bundled)

**Comment by pBread** [comment]
Hmmm... maybe I was running into an issue with `yarn link`. I'll try removing the globals and let you know.

**Comment by developit** [comment]
Seems like this is more of a yarn issue than a Microbundle issue. Can we close?

**Comment by nicholasio** [comment]
I'm also having this issue, tried to use microbundle and it's including react even though react is a peerDependency

**Comment by wardpeet** [comment]
Hi @nicholasio!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

**Comment by BrandonMA** [comment]
As @ForsakenHarmony said, peerDependencies and dependencies are not bundled, but if you have react as a dependency, yarn will create a node_modules folder inside your library, so you actually have 2 react instances, the solution is to set react as peerDependencies, because that way you are letting yarn(or npm for this matter) know that it should use the global react package installed on that project.

This is not a problem with microbundle, but how you setup your package.json. I hope you find this explanation useful.

**Comment by mikestopcontinues** [comment]
For me, the solution was to get rid of the `umd` export. For some reason (webpack or babel or NextJS?) was selecting that version, even though my package.json had all of the options available... And that particular build had the problem. React was VERY DEFINITELY getting included, and it was listed as a peer. (That said, it was also listed in the devDeps—is that possibly the bug? Because peers in devDeps should still be excluded.)

Anyway, here's my [failing package.json](https://github.com/sitearcade/react-hooks/blob/v0.0.13/package.json), and my winning [package.json](https://github.com/sitearcade/react-hooks/blob/v0.0.14/package.json).

**Comment by reevesryan** [comment]
I was also seeing `react` being bundled even though it was listed in `devDependencies` and `peerDependencies`. The solution for me was to add the `prop-types` package to the `devDependencies`

**Comment by developit** [comment]
Hmm - so it seems like Microbundle might be bundling dependencies of dependencies that are peers somehow? Seems strange.

**Comment by developit** [comment]
@mikestopcontinues just an update - Next.js prefers CJS/UMD over ESM when bundling for the server. This doesn't align with any other bundler, so it's not something that makes much sense to account for in Microbundle.

In your failing package.json, the UMD build was being passed with `--external none`. That will inline all dependencies regardless of their presence in "dependencies" fields, causing the hooks error.

**Comment by mikestopcontinues** [comment]
@developit Thanks for the tips. I'm not even sure what path lead me to include `--external none`. I'll take another look!

**Comment by tkumpanenko** [comment]
@mikestopcontinues did you find a solution for next.js?

**Comment by mikestopcontinues** [comment]
I did! Here's an example solution:

```json
{
  "source": "src/index.js",
  "main": "./dist/index.js",
  "jsnext:main": "./dist/index.modern.js",
  "module": "./dist/index.module.js",
  "syntax": {
    "esmodules": "./dist/index.modern.js"
  },
  "exports": {
    ".": {
      "browser": "./dist/index.module.js",
      "import": "./dist/index.module.js",
      "require": "./dist/index.js"
    }
  },
  "files": [
    "dist"
  ],
  "scripts": {
    "build": "microbundle --no-compress -f cjs,esm,modern --jsx React.createElement --jsxImportSource react"
  },
}
```

**Comment by wendellpbarreto** [comment]
@mikestopcontinues i'm using the bundle for next.js with the above config but without any success, can you take a look and maybe help me?

```
"source": "src/index.js",
  "main": "./dist/index.js",
  "jsnext:main": "./dist/index.modern.js",
  "module": "./dist/index.module.js",
  "syntax": {
    "esmodules": "./dist/index.modern.js"
  },
  "exports": {
    ".": {
      "browser": "./dist/index.module.js",
      "import": "./dist/index.module.js",
      "require": "./dist/index.js"
    }
  },
  "files": [
    "dist"
  ],
  "dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "react-scripts": "4.0.3",
    "prop-types": "^15.7.2",
    "web-vitals": "^1.0.1"
  },
  "peerDependencies": {
    "bootstrap": "^4.6.0",
    "clsx": "^1.1.1",
    "next": "^10.0.9",
    "perfect-scrollbar": "^1.5.0",
    "prop-types": "^15.7.2",
    "react": "^17.0.2",
    "react-bootstrap": "^1.5.2",
    "react-dom": "^17.0.2",
    "react-inlinesvg": "^2.2.2",
    "react-perfect-scrollbar": "^1.5.8"
  },
  "devDependencies": {
    "@babel/cli": "^7.13.10",
    "@babel/preset-react": "^7.12.13",
    "microbundle": "^0.13.0",
    "node-sass": "^5.0.0",
    "npm-run-all": "^4.1.5",
    "prop-types": "^15.7.2"
  },
  "scripts": {
    "build": "microbundle --no-compress -f cjs,esm,modern --jsx React.createElement --jsxImportSource react",
    "dev": "microbundle watch --no-compress -f cjs,esm,modern --jsx React.createElement --jsxImportSource react",
    "clean": "rm -rf dist",
    "prepare": "run-s build",
    "test": "run-s test:unit test:lint test:build",
    "test:build": "run-s build",
    "test:lint": "eslint .",
    "test:unit": "cross-env CI=1 react-scripts test --env=jsdom",
    "test:watch": "react-scripts test --env=jsdom"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "babel": {
    "presets": [
      "@babel/preset-react"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```

![image](https://user-images.githubusercontent.com/2782873/112344037-775b6100-8ca2-11eb-9708-7c6251f31e7b.png)

**Comment by mikestopcontinues** [comment]
@wendellpbarreto It doesn't look like the problem is with microbundle. If you look at the stack trace, is useConfigContext actually being called from within a component? It's got to be direct too. You can't do `<Component> => someFunc() => useConfigContext()`. It would have to be `<Component> => useSomeFunc() => useConfigContext()`.

If your hook is in the right place, I'm sure I can help. I've only ever gotten that error when I refactor a hook to someplace it shouldn't be. I really don't think it's microbundle.

**Comment by wendellpbarreto** [comment]
@mikestopcontinues i understand you perfectly. I made a intentional use of useState at the top level component exported in my package, and as you can see, seems like i can't use any hook inside the components.

The code:
![image](https://user-images.githubusercontent.com/2782873/112366074-21dd7f00-8cb7-11eb-9fc6-64dca002c994.png)


The error:
![image](https://user-images.githubusercontent.com/2782873/112365878-eb9fff80-8cb6-11eb-9f0d-b0aa706f6985.png)

**Comment by mikestopcontinues** [comment]
Gosh, this is a hard one. Maybe it has to do with [3] in the error message? Does your nextjs app use the same version of react as your package (^17.0.2)? It could be you ended up with two different versions in there. You can try to inspect the bundle with webpack bundle analyzer or webpack inspectpack duplicates plugin. Otherwise, I've got no idea. The bundled code honestly looks fine to me.

**Comment by developit** [comment]
You should use a much wider react version range. Npm 7 installs peer dependencies now, witch can lead to two react versions.

**Comment by programarivm** [comment]
> I think this is still an issue that needs some clarification and/or documentation. Can anyone elaborate on best-practices for avoiding conflicts like these? i.e. accidentally creating two versions of a dependency.

@pBread if this symlink issue is still tricky when developing nmp packages on a local environment, you may want to use [install-local](https://www.npmjs.com/package/install-local) for dev purposes.

See:

- [How to run React Board](https://github.com/chesslablab/react-board/blob/main/CONTRIBUTING.md#how-to-run-react-board)

I hope this will be helpful.
