### ISSUE TITLE
Incorrect transform with async/await

### ISSUE THREAD

**Issue by CyriacBr** [developit/microbundle#565]
microbundle uses the babel plugin `babel-plugin-transform-async-to-promises` which has this [serious bug](https://github.com/rpetrich/babel-plugin-transform-async-to-promises/issues/49) as it changes the behavior of your code once transpilled.  
Sharing that here as this could save a few hours of headache and insanity to someone. I wasn't that lucky.

**Comment by developit** [comment]
For sure. I think short term we can detect switch cases within async functions and throw an error.

**Comment by Djaler** [comment]
@developit so what about it?

**Comment by developit** [comment]
@Djaler this is an upstream issue that needs to be fixed in the Babel plugin.

**Comment by Djaler** [comment]
> @Djaler this is an upstream issue that needs to be fixed in the Babel plugin. 

I mean this :
```
we can detect switch cases within async functions and throw an error
```

**Comment by Djaler** [comment]
Also, you can just stop using this plugin

**Comment by developit** [comment]
@Djaler the value proposition of microbundle is that output is unabashedly minimal. Switching to regenerator output would be a very large step in the wrong direction. That being said, depending on how modern output moves forward, it might be possible to sacrifice some of the output quality in legacy builds as long as most package consumers end up with the modern version. Currently that's not the case, but it may be soon.

**Comment by Djaler** [comment]
By `sacrifice quality` you mean wrong, not working code?

**Comment by PeterBurner** [comment]
is there a workaround for now?  
will things break if we pin `babel-plugin-transform-async-to-promises` to v0.8.14?  
or do we have to downgrade to `microbundle` v0.11.0  ?

**Comment by Nick-Lucas** [comment]
> the value proposition of microbundle is that output is unabashedly minimal. Switching to regenerator output would be a very large step in the wrong direction

Given that the upstream package hasn't had a commit since October 2019, and this critical bug was reported way back then, wouldn't it be a good idea to look at alternatives from shipping a broken dependency? If there's a working version that could be pinned like @PeterBurner suggests, then that's great, but regenerator is very common in the wild, so it doesn't really seem like a bad choice if it's actually stable.

**Comment by developit** [comment]
The workaround is to avoid direct combined usage of async/await and switch. We can't produce acceptable output for it with or without regenerator, so consider it unsupported by Microbundle.

The fact that regenerator is common does not make it the right solution. Regenerator is routinely duplicated tens or hundreds of times in bundles because a large percentage of npm modules bundle it for the sake of correctness. Unfortunately, no tools exist that can fix that situation, which leaves us with two bad options: ship regenerator and bloat 16,000 npm modules, or ship async-to-promises and advise Microbundle users to avoid the problem syntax. We only transpile first-party code, so this only applies to code written by the person configuring the bundler - the code that is easiest and most valuable to change.

Ultimately, Microbundle isn't webpack or Rollup - it's not a general-purpose tool and it doesn't cater to the same breadth of use-cases. It exists purely to provide the smallest output for the subset of modern input that we be compiled with minimal overhead. This particular async/await issue is gnarly, sure, but keep in mind Microbundle and indeed most meta-bundlers run Babel in loose mode anyway, which has far more edge cases in order to produce output of an acceptable size.

I have yet to find any reasonable solution to this aside from advocating for modern JS output that is (thankfully) immune to the problem, which is exactly what we are doing. Once enough bundlers _(or really bundler configs)_ support modern npm modules, this problem goes away entirely. At that time, we can happily switch to generating larger more accurate ES5 bundles for the rare cases in which someone would end up using them.

**Comment by fbbdev** [comment]
Hello, this is not only about switches, I'm seeing this in for/while loops both with break and continue statements (as reported also in rpetrich/babel-plugin-transform-async-to-promises#49) and it's seriously violating code semantics. There are many common cases where performance will drop a lot if one cannot reliably break out of a loop. This is a big problem.

**Comment by make-github-pseudonymous-again** [comment]
Upstream allegedly fixed with https://github.com/rpetrich/babel-plugin-transform-async-to-promises/issues/49 18 days ago.

**Comment by PeterBurner** [comment]
> Upstream allegedly fixed with [rpetrich/babel-plugin-transform-async-to-promises#49](https://github.com/rpetrich/babel-plugin-transform-async-to-promises/issues/49) 18 days ago.

Is there some action required on microbundle side? Eg. updating dependencies.
Or can this issue be closed?

**Comment by developit** [comment]
@peterburner I believe a new publish of Microbundle would automatically include this as long as we run `npm update`. Might be better to submit a PR with the part release of this transform bumped though.
