### ISSUE TITLE
the packaged  does not import the css file

### ISSUE THREAD

**Issue by lvzegeng** [developit/microbundle#567]
Why do I use import './index.css'; in the code, but the packaged .mjs does not import the index.css file

**Comment by marvinhagemeister** [comment]
Because importing non-js files is something that's not part of any spec (yet) and thus it's a special features of bundlers. Executing code that requires/imports `*.css` files in node would result in a crash. That's why bundlers like webpack and rollup (which microbundle is based on) typically stringify the contents into an js file. Microbundle is built with the aim to produce a single file at the end, which makes imports unnecessary. That's why you won't find them in the output files.
