### ISSUE TITLE
Support/build dependencies with pkg.source

### ISSUE THREAD

**Issue by MatejBransky** [developit/microbundle#672]
Hi, 

Parcel.js v1 supports building of dependencies which they have the `source` attribute in `package.json`. It's useful if you use monorepo strategy but Parcel.js is meant for a building apps and we would like to use something similar (0 config bundler) for our packages. Microbundle looks great but this missing feature is crucial for us because without that we would need to build graph of dependencies and firstly build packages without any dependency to other companys packages and then continue to next dependents..

Is that possible?

**Comment by developit** [comment]
"source" is meaningless, since it can point to code written in an arbitrary version of JS or TS, and can rely on nonstandard syntax like JSX or decorators. The only way to implement support for that in a bundler is to support every possible permutation of source format, which is extremely bad for performance and generally doesn't align with Microbundle's goal of being a simple solution that works for 90% of modules. 

Fwiw I don't think you need parcel-style source dependencies for the setup you described. If you are truly using dependencies, each should be compiled to the formats needed by your consumers (in this case, your other modules), and the compiled output should be published somewhere or committed. This works nicely with Microbundle as long as your chosen tool for managing the monorepo is capable of running builds/publishing only changed packages - I believe yarn can do this.

**Comment by MatejBransky** [comment]
Thanks for your reply. 

Yeah this does make sense. I've used lerna run command which respects topological order of packages so there aren't any problems with missing dist folders. That solved my issue.

Btw: The only advantage is right within a developed application where you can skip deps watchers because if you have strictly defined environment in a monorepo (e.g. TS, same syntax features, companies ussually have the same setup for packages and apps) then you can execute one watcher for the app and all deps with the `pkg.source` attribute are watched too so you don't need any other watchers and you have immediate update. For that we use Parcel.
