### ISSUE TITLE
Scoped npm package doesn't resolved without explicit path including node_modules

### ISSUE THREAD

**Issue by dubaua** [developit/microbundle#686]
Hello.

I'm using microbundle for bundling a small JS library that internally uses another my JS library bundled with microbundle.

Both libraries are scoped in my username on npm, because many good and short names already taken. So, my problem is I should explicitly write this:
```js
import mergeOptions from '/node_modules/@dubaua/merge-options';
```
instead of this:
```js
import mergeOptions from '@dubaua/merge-options';
```
If I'm doing as second line above I'm getting warnings on building:
```
'/node_modules/@dubaua/merge-options' is imported by get-declension.js, but could not be resolved – treating it as an external dependency
No name was provided for external module '/node_modules/@dubaua/merge-options' in output.globals – guessing 'mergeOptions'
```
And the dependent library is not included in the JS bundle.

This is not a big problem on my [get-declension](https://github.com/dubaua/get-declension) library, but I have worst issue with another library, that I cannot bundle at all.

Possibly this strange thing more related to rollup, I don't know.

I will greatly appreciate any help or suggestions are.

**Comment by marvinhagemeister** [comment]
That's because node only supports either relative file paths that start with `./` or `../` and everything else is treated as a module import from `node_modules`. Meaning `@foo/bar` resolves to `node_modules/@foo/bar`. Therefore the `/node_modules/@dubaua/merge-options` path falls into the later category and will be resolved wrongly.

**Comment by developit** [comment]
The correct syntax is to use a bare specifier:

```js
import mergeOptions from '@dubaua/merge-options';
```

None of the docs suggest using `/node_modules/` or indicate that doing so is supported.

---

I think it's possible you tried adding `/node_modules` after getting a "could not be resolved" error, so I'll explain what causes that and the solution:

If you're seeing the message `'@dubaua/merge-options' is imported by src/index.js, but could not be resolved – treating it as an external dependency`, that's because you have installed the dependency incorrectly.   There are two ways you can install a dependency:

1. to **bundle a copy** of the dependency into your module:

    ```jsonc
    {
        "peerDependencies": {
            "@dubaua/merge-options": "^2.0.0"
        },
        // (and if you need it during development):
        "devDependencies": {
            "@dubaua/merge-options": "^2.0.0"
        }
    }
    ```

2. to leave the module as **an external dependency** of your module:

    ```jsonc
    {
        "dependencies": {
            "@dubaua/merge-options": "^2.0.0"
        }
    }
    ```

Choosing the correct location in `package.json` matters, since Microbundle uses this to determine how to bundle your code.

**Comment by dubaua** [comment]
Please, let me clarify following:
Am I get it right that if I want my library bundle include **a copy of merge-options**, I should install it as devDependency? I'm doing it right now, but there is **a links to merge-options** in my `dist/`

I've tried to remove `/node_modules` completely, I thought it may be cache problem, but no luck.

Maybe I missing some flags in my build command? I've tried with `--external none` and without it.

**Comment by developit** [comment]
Apologies, I realized my explanation there wasn't super great. Here's the main things:

1. there's never a reason to prefix with `/node_modules`. That creates a bundle that depends on a file in a `node_modules` directory at the root of your hard drive.

2. if you want to bundle a copy of merge-options, install it as a devDependency. Check that it's listed _only_ in `"devDependencies"` in your package.json, not in "dependencies" or "peerDependencies" - if something is listed under either of those two keys, it will be marked as external and not bundled.

There's no need for `--external` here, that option is for very rare edge-cases like Electron.
