### ISSUE TITLE
Provide a flag to verify max bundle size 

### ISSUE THREAD

**Issue by StarpTech** [developit/microbundle#717]
As titled. Example:

```
microbundle -i lib/main.js -o dist/bundle.js --max-bytes 1000
```

**Comment by wardpeet** [comment]
Hey @StarpTech,

Verifying bundle sizes are a must if you want to keep your project on a budget. This feature lives a bit out of microbundles focus area. There are tools like https://github.com/siddharthkp/bundlesize that do just what you ask for and can be complementary to microbundle.

I'll keep this open for a few days so other maintainers/community members can comment on it.

**Comment by developit** [comment]
I'm 50/50 on this one. Since we're already computing the compressed sizes, it would be easy to add. But there are so many variables here that don't seem to have a one-size-fits-all answer... should the build fail when size passes that threshold? which output bundle(s) does the threshold apply to? which compression type is it based on?

Right now doing assertions on Microbundle's output also kinda works:

`microbundle --raw 2>&1 | grep -Eom1 '\d+ B' | cut -d' ' -f1`

... which could be used to do something like this:

```json
{
  "maxSize": "1000",
  "scripts": {
    "bundle": "microbundle --raw",
    "build": "x=`npm run -s bundle | grep -Eom1 '\\d+ B' | cut -d' ' -f1` && (test $x -lt $npm_package_maxSize || echo \"Error: $x > $npm_package_maxSize\" && exit 1)",
  }
}
```

**Comment by developit** [comment]
I think we're going to make the call that this is out of scope. Bundle size assertions should happen after bundling, and are more of a testing/CI concern. There are some really awesome tools for this already, and we couldn't make Microbundle compare to them without adding tons of configuration options.
