### ISSUE TITLE
any documention for create a babel macro?

### ISSUE THREAD

**Issue by latel** [developit/microbundle#725]
I tried to bundle babel macro as descriped here https://github.com/developit/microbundle/tree/master/test/fixtures/macro, but no luck.

how to reproduce:

1. git clone https://github.com/latel/jvutil
2. npm run build:mathmacro

**Comment by marvinhagemeister** [comment]
FYI: For anyone trying to reproduce it: There is a missing instruction. You need to switch to the `feature/macro-math` branch to be able to reproduce it. I was initially confused because there is no mention of the word `macro` anywhere in the default branch on checkout.

For completeness sake: Here is the error output:

```bash
(babel plugin) TypeError: /oss/jvutil/mathmacro/src/index.js: ./macro: Cannot read property 'left' of undefined
TypeError: /oss/jvutil/mathmacro/src/index.js: ./macro: Cannot read property 'left' of undefined
    at traverse (/oss/jvutil/mathmacro/src/macro.js:28:14)
    ...
```

Reading the error message, it seems like it suggests that we try to access a property of an object in `macro.js` that doesn't exist. The section the stack trace points to looks like this:

```js
function traverse(node) {
  let arg = [];
  if (node.left.type === "BinaryExpression") { // <- Error is thrown here
    arg[0] = traverse(node.left);
  } else {
    arg[0] = node.left;
  }
  ...
}
```

Adding a quick `console.log(node)` at the top of the function reveals that we're not getting anything. The `traverse` function is called with `undefined` instead of an AST-node. So let's check where `traverse` is called. The first call to `traverse` is at the bottom of the custom macro:

```js
path.parentPath.replaceWith(traverse(args));
```

So if we receive `undefined` _inside_ `traverse`, then we can make the assumption that the variable `args` is `undefined`. Again, this assumption is confirmed by adding another `console.log`. Following the trail back to where the variable `args` is initialized, we end up at this line:

```js
const args = getInitArguments(path);
```

and the body of that function looks like this:

```js
function getInitArguments(path) {
  const callExpression = path.findParent((p) => t.isCallExpression(p));
  return callExpression.node.arguments[0];
}
```

Doing a quick `console.log` again we can see that the variable `path` holds the correct value. This hints to us that something inside `getInitArguments` is wrong. Logging out the value of `callExpression` reveals, that it's correct. But inspecting the logged output further, we can see that the function has **no** arguments.

```js
Node {
  type: 'CallExpression',
  start: 49,
  end: 56,
  loc: SourceLocation { start: [Position], end: [Position] },
  callee: Node {
    type: 'Identifier',
    start: 49,
    end: 54,
    loc: [SourceLocation],
    name: 'macro',
    leadingComments: undefined,
    innerComments: undefined,
    trailingComments: undefined
  },
  arguments: [], // <-- Woa, no arguments here!
  leadingComments: undefined,
  innerComments: undefined,
  trailingComments: undefined
}
```

And that's why the macro fails. It assumes that every CallExpression has arguments, but that's very much not true in reality. Many codebases have functions which are called without arguments.

The interesting bit is why the macro is already firing here. Looking at the package name I'm assuming that you want to export the macro for other users to be able to use. Problem is, that that is not what the code is doing. Instead of exporting the macro, it calls it immediately:

```js
const macro = require('./macro');
export default macro();
```

On top of that mixing CommonJS and ESModule syntax is invalid JavaScript. You need to pick one or the other, not both at the same time. `microbundle` kinda makes that decision for you as it only supports the ESModule syntax as the input format. So the correct content of `index.js` should look like this:

```js
// Content of index.js
export { macro as default } from './macro';
```

Because `macro.js` is using CommonJS instead of ESModules we need to fix that too:

```js
export const macro = createMacro(mathMacro);
```

And now we got a working macro :tada: 

## Conclusion

As quick way to check where an error is coming from, one can look at the stack trace that's printed in the terminal. The first two lines point to code in this repo and not at `microbundle` or any other module inside `node_modules`. This is a 99.99% guarantee that the error is caused in the code in the repo.

```bash
 at traverse (/oss/jvutil/mathmacro/src/macro.js:27:14) // <-- Points at code in repo
 at mathMacro (/oss/jvutil/mathmacro/src/macro.js:61:31) // <-- Points at code in repo too
```

The other thing to be careful when writing babel plugins is to be aware of any assumptions one makes. They may often turn out to be wrong. In this case the erroneous assumption is that the plugin assumes that every function is called with arguments.

Hope this help :+1:

**Comment by latel** [comment]
thanks very much, sorry for the inconvenience.
 
it seems I mis-understand the docs(https://github.com/developit/microbundle/tree/master/test/fixtures/macro) out there, it describes how to use babel macro not how to build one.
