### ISSUE TITLE
How to target IE11 using microbundle?

### ISSUE THREAD

**Issue by ydennisy** [developit/microbundle#761]
I am using microbundle and typescript. I have followed the advice and set target and module to `esnext`, and have tried to add a browserslist key in the package.json, but the build from microbundle does not differ with various settings.

My command:

```
	npx --no-install microbundle \
	  -i src/index.ts \
	  -o dist/sdk/edgekit.min.js \
	  -f umd \
	  --pkg-main false \
	  --compress true \
	  --external none \
	  --sourcemap \
```

**Comment by developit** [comment]
@ydennisy what value were you providing for the `"browserslist"` key?  The default output for the `umd` target should already be IE11-compatible, but it doesn't auto-polyfill things.

**Comment by ydennisy** [comment]
@developit thanks for your reply.

It seems my understanding is a little off - my thought was that this would convert uses of things such as fetch to something compatible for IE11, so what would be the best practice for making the bundle actually run on IE11, would we manually have to maintain what we used and the polyfills from something like `core-js`?

**Comment by developit** [comment]
Microbundle only polyfills JS language features. It doesn't do DOM polyfilling because it's too unreliable to do correctly. 

In general if you're using a DOM API that isn't supported in the browsers you're targeting, it's best to import that polyfill yourself. General-purpose automatic polyfilling is one of those things that sounds good in theory, but in practise it does more harm than good.

For fetch, if you're just using the basic fetch() function (not the Headers API), you might find [Unfetch](https://github.com/developit/unfetch) fits the bill - it's 500b and supports IE9+. 

For Promise I always recommend the `promise-polyfill` package - it's 1kb and does reasonable deferral scheduling in IE.

**Comment by ydennisy** [comment]
@developit thanks very much for this - huge help!

One final question: is there any automated way / best practice to test / analyse code for suitability for browsers?

From my current understanding browserstack is an option - or just running tests in all the browsers. 

I was wondering if there is a static analysis tool which will flag DOM APIs which are not present in all targeted browsers?

Thanks again.
Dennis

**Comment by Antonio-Laguna** [comment]
@developit I was checking this as I was releasing a library using microbundle and I get untranspiled code which would deem this not usable on IE11 and I think it also is different with what the README.md says.

I'm not getting `const` nor `class` transpiled which is creating issues since by default node_modules aren't transpiled. I'm just using recommended settings here: https://github.com/firstandthird/domodule/blob/main/package.json

Yet I get

<img width="511" alt="Screenshot 2020-12-03 at 17 25 25" src="https://user-images.githubusercontent.com/946645/101057635-8a7be100-358c-11eb-8608-0a31d20c906c.png">

**Comment by rschristian** [comment]
@Antonio-Laguna That's the ESM output you're looking at, which is, at a minimum (not sure on specifics), ES6. That is transpiled as you will see differences between it and the modern output (if you're using newer features).

If you want IE you're going to need to use the CJS or UMD outputs (`domodule.js` and `domodule.umd.js`)

**Comment by Antonio-Laguna** [comment]
ESM should be transpiled without any imports working since Babel doesn't transpile node modules (by default), hence what you get is untranspiled code all the way which is undesired. 

Also, this is from the README.

![Screenshot 2020-12-03 at 19 01 41](https://user-images.githubusercontent.com/946645/101069224-fdd81f80-3599-11eb-8b22-2ce40dc26c3c.png)

See how `let` gets converted into `var`? Also, UMD has the same behavior in which `class` and `const` stay.

**Comment by rschristian** [comment]
@Antonio-Laguna UMD having `class` and `const` is definitely an issue but, as far as I'm aware, ESM containing `let` and `const` is perfectly fine. 

I'm at work now, so can't check, but this might be that babel config you have in the repo.

**Comment by Antonio-Laguna** [comment]
I don't think it's fine given the screenshot and given Babel thing. How do you use modules without transpiling node_modules? 

Also... 🤦 that babel thing was messing it out and I completely disregarded it. Thanks a lot! Doing that gets rid of `const` everywhere.

**Comment by rschristian** [comment]
> I don't think it's fine given the screenshot and given Babel thing. How do you use modules without transpiling node_modules?

Well I do believe it *should* be fine, but not an expert here. Generally I don't transpile `node_modules`. Libraries should provide the right targets or that's the job for an application tool to handle. Using `dependencies` with Microbundle should push the `node_modules` issue downstream to the the application level where they can decide how they want to handle that.

> Also... 🤦 that babel thing was messing it out and I completely disregarded it. Thanks a lot! Doing that gets rid of `const` everywhere.

Glad that worked.

**Comment by ydennisy** [comment]
@developit sorry to bring this up again, but I have not been able to find instructions on how one might use microbundle to ponyfill promises when using async / await.

The project is a lib which will be used in 3rd party web pages, so we must avoid overwriting any globals. Right now we are using microbundle without any extra configuration.

**Comment by developit** [comment]
@ydennisy The following `babel.config.js` should work: (remember to `npm install --save-dev promise-polyfill`)

```js
// babel.config.js
module.exports = {
  plugins: [
    ({ template }) => ({
      name: 'transform-inject-promise',
      visitor: {
        Identifier(path, state) {
          if (state.p || !(path=path.resolve()).isIdentifier({name:'Promise'}) || path.scope.getBinding('Promise')) return;
          state.p = path.scope.getProgramParent().path.unshiftContainer('body', template.ast`import Promise from'promise-polyfill'`);
        }
      }
    })
  ]
}
```

([demo of the plugin](https://astexplorer.net/#/gist/e9c3be6984f84d54f988055147b420cf/8071349da8008225feb0c4a21f1364f3f8f69b74))

**Comment by ydennisy** [comment]
@developit that is incredible thanks!

**Comment by ydennisy** [comment]
@developit sorry to have to open... again :) 

```
(babel plugin) TypeError: Cannot read property 'resolved' of undefined
TypeError: Cannot read property 'resolved' of undefined
    at /Users/dennisyurkevich/dev/edgekit-platform/wrapper/node_modules/microbundle/dist/cli.js:229:146
    at Array.findIndex (<anonymous>)
    at /Users/dennisyurkevich/dev/edgekit-platform/wrapper/node_modules/microbundle/dist/cli.js:229:48
    at Array.forEach (<anonymous>)
    at /Users/dennisyurkevich/dev/edgekit-platform/wrapper/node_modules/microbundle/dist/cli.js:227:23
    at Array.forEach (<anonymous>)
    at mergeConfigItems (/Users/dennisyurkevich/dev/edgekit-platform/wrapper/node_modules/microbundle/dist/cli.js:226:22)
    at config (/Users/dennisyurkevich/dev/edgekit-platform/wrapper/node_modules/microbundle/dist/cli.js:348:32)
    at transformCode (/Users/dennisyurkevich/dev/edgekit-platform/wrapper/node_modules/@rollup/plugin-babel/dist/index.js:239:86)
    at async ModuleLoader.addModuleSource (/Users/dennisyurkevich/dev/edgekit-platform/wrapper/node_modules/rollup/dist/shared/rollup.js:18335:30)
```

This error is happening on the a ConfigItem which has no name or file:

```
ConfigItem {
  value: [Function],
  options: undefined,
  dirname: '/Users/dennisyurkevich/dev/edgekit-platform/wrapper',
  name: undefined,
  file: undefined
}
```

From this line:
```
// line 229 in dist/cli.js
      const itemToMergeWithIndex = mergedItems.findIndex(mergedItem => (mergedItem.name || mergedItem.file.resolved) === (item.name || item.file.resolved));

```

**Comment by developit** [comment]
@ydennisy I think the solution will have to be to make the plugin its own module:

```js
// babel.config.js
module.exports = {
  plugins: [
    require.resolve('./transform-inject-promise.js')
  ]
}
```

```js
module.exports = ({ template }) => ({
  name: 'transform-inject-promise',
  visitor: {
    Identifier(path, state) {
      if (state.p || !(path=path.resolve()).isIdentifier({name:'Promise'}) || path.scope.getBinding('Promise')) return;
      state.p = path.scope.getProgramParent().path.unshiftContainer('body', template.ast`import Promise from'promise-polyfill'`);
    }
  }
});

```

**Comment by ydennisy** [comment]
This works!
