### ISSUE TITLE
[...new Array(n)].map(...) incorrectly changed to [].concat(new Array(n)).map(...)

### ISSUE THREAD

**Issue by n8jadams** [developit/microbundle#820]
microbundle-crl version: 0.13.11

I have a React component that does the following:
```jsx
return (
  <div>
  {[...new Array(pageCount)].map((_, pageNumber) => {
	  return (
		  <a
			  key={pageNumber}
		  >
			  {pageNumber + 1}
		  </a>
	  )
  })}
  </div>
)
```

When I run my development script, (`$ microbundle-crl --watch --no-compress --format modern,cjs`), it transpiles to something like this
```jsx
return React.createElement("div", null, [...new Array(pageCount)].map(function (_, pageNumber) {
	return React.createElement("a", {
		key: pageNumber,
	}, pageNumber + 1);
})));
``` 
So far so good, it's retaining what I wrote essentially, just transpiling the jsx,

but when I run my build script, (`$ microbundle-crl --no-compress --format modern,cjs`):
```jsx
return React.createElement("div", null, [].concat(new Array(pageCount)).map(function (_, pageNumber) {
	return React.createElement("a", {
		key: pageNumber,
	}, pageNumber + 1);
})));
```

This is causing this component to not render at all when I build the script. A quick run without `no-compress` and it looks like the same effect. Odd that any transpilation aside from the JSX would take place.

**Comment by wardpeet** [comment]
We don't do anything special between watch & regular builds so I'm curious about what microbundle-crl is doing differently

When I use microbundle
```js
[...new Array(pageCount)].map((_, pageNumber) => {
  console.log(pageNumber);
});

```
converts to 
```js
[].concat(new Array(pageCount)).map(function(n,o){console.log(o)});
```

As stated, this is slightly tangential to microbundle, and it seems like we’ve provided enough information to make an informed decision.

If this is not the case, or if we can help further--please don’t hesitate to reach out or comment on this issue, and we’d love to take another look.

**Comment by AlbertoPravisano** [comment]
@n8jadams Could you share your build script? I have the same problem. I have converted my script from
`microbundle-crl --no-compress --no-css-modules --no-sourcemap --format modern,cjs`
to
`microbundle --no-compress --no-css-modules --no-sourcemap --format modern,cjs --jsx React.createElement --jsxFragment React.Fragment`

It seems a problem with globals since `[...new Array(nLines).keys()]` does not return an array of increasing numbers but returns an empty object `[{}]` and `[...new Array(nLines)].map((_, index) => console.log(index))` prints nothing on console, but both codes works in the browser's dev tools console and in a project builded with react-scripts

**Comment by n8jadams** [comment]
@AlbertoPravisano I'm sorry I've long since switched projects and don't recall where this original build script is, but as you can see in my original post, I ended up using `microbundle` instead of `microbundle-crl` to fix this problem.
