### ISSUE TITLE
The zero-configuration bundler for tiny modules

### ISSUE THREAD

**Issue by oshalom-dcg** [developit/microbundle#831]
Why you use the word **tiny**? I am currently using micro bundle for an entire component library and it works perfectly fine

**Comment by developit** [comment]
It's not designed for larger use-cases, even if it happens to work okay for them.

**Comment by Shakeskeyboarde** [comment]
Even though this is closed, I'm going to give a slightly more detailed answer.

Because microbundle creates a single JS file, the library no longer supports tree shaking. Any time you import a single component, you will incur the entire library size as a cost in your web app bundle.

That being said, you could use microbundle as part of a mono-repo, so that each component and utility is it's own microbundled library. But it may be more trouble than it's worth.
