### ISSUE TITLE
target web and nodejs

### ISSUE THREAD

**Issue by TimDaub** [developit/microbundle#832]
Hi,

I have a package that can work both on the web and on node.js. I couldn't find an option that'd allow me to do both.
Now I'm using `microbundle --target node`

**Comment by Shakeskeyboarde** [comment]
How does the `--target` option change the build?

**Comment by TimDaub** [comment]
Yes, for `--target node` the build will be runnable on nodejs and vice versa for "web"

**Comment by developit** [comment]
`--target node` just avoids transpiling things like classes that are well-supported in Node, and disables Terser minification by default. If you're building a library that works in both environments, you should use the default which is `--target web`.

**Comment by flo-sch** [comment]
I am struggling a bit with the target as well: I have a TS project I would like to compile only for node (no web support needed), but when I run this script:

(Sorry if the issue is unrelated, I landed here after a search 😅)

```json
{
  "source": "src/index.ts",
  "main": "dist/index.js",
  "module": "dist/index.esm.js",
  "types": "dist/index.d.ts",
  "scripts": {
    "build": "microbundle --target node --tsconfig tsconfig.build.json"
  }
}
```

I got the warning:

> Creating a browser bundle that depends on Node.js built-in modules ("path", "os", "stream" and "tty"). You might need to include https://github.com/ionic-team/rollup-plugin-node-polyfills

Just in case, I also have a `babel.config.json` file that I need for among others things `jest`:

```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "current"
        }
      }
    ],
    "@babel/preset-typescript"
  ]
}
```

Is it intentional or am I missing something to only target node?

**Comment by developit** [comment]
Is that with the latest version of Microbundle? Worst case it's a warning and can be ignored.

**Comment by flo-sch** [comment]
> Is that with the latest version of Microbundle? Worst case it's a warning and can be ignored.

v0.13, but I think I figured it out :)

(My use-case is a TypeScript module only meant for node.js environment)

1. even without a `umd:main` key in my package.json, `microbundle` was generating an UMD bundle (AFAIR, it did not in v0.12 if the key was not set, but I probably missed that change), I fixed that by specifying the formats: `microbundle --format cjs,esm`
2. my generated bundle was unreasonably big (~500kb against an expected ~3kb), and I initially thought it was because of a wrong format / target. A lot of additional dependencies were compiled into the bundles that were not part of my source code. I eventually figured what was the reason: I simply forgot to reference one imported module in the `dependencies` of my package.json 😅 (And it still "worked" since it was itself a transitive dependency of another direct dependency)

So anyway, with that final command and properly defined dependency tree, I got my bundles back to their expected size:

```bash
microbundle --target node --tsconfig tsconfig.build.json --format cjs,esm
```

Sorry for disturbing then 😇
