### ISSUE TITLE
Object spread seems to be failing

### ISSUE THREAD

**Issue by HenrikJoreteg** [developit/microbundle#86]
Looks like buble supports it, as long as you pass an option for `objectAssign: 'Object.assign'` but in practice it doesn't seem to be working.

My code:

```jsx
import { h } from 'preact'

export default ({ title, ...rest }) => (
  <div {...rest} className={`${rest.className}`} />
)
```

Output:

```
SyntaxError: Unexpected token (3:25) /some/path/page.js (nodent)
export default ({ title, ...rest }) => (
-------------------------^
```

**Comment by olstenlarck** [comment]
The problem is in Rollup as i remember.

**Comment by tlvince** [comment]
I just ran into this. One quick workaround is to transpile with babel's transform-object-rest-spread first, then run microbundle on the intermediary output, e.g. in [crosslink](https://github.com/tlvince/react-router-crosslink/blob/1ce2b6aad7f001e1dbea36ba76877ec8bbcda94e/package.json#L8-L11).

**Comment by olstenlarck** [comment]
Update Rollup to 0.56, it now support ecmaVersion: 9.

**Comment by MobiusHorizons** [comment]
is there a workarround in the mean time, or can we simply not use object spread with microbundle until it gets fixed upstream?

**Comment by tlvince** [comment]
@MobiusHorizons you can pre-transform it through `babel` for now, e.g. https://github.com/tlvince/react-router-crosslink/blob/1ce2b6aad7f001e1dbea36ba76877ec8bbcda94e/package.json#L8-L11

**Comment by olstenlarck** [comment]
And if someone want to contribute, there are few things that may be done to help.

1. Implement ESPree (not the ESTree one) plugin into `babylon` - https://github.com/babel/babel/issues/7369
2. PR needed small changes to Rollup to use `babylon` with the ESPree plugin by default, because it needs the ESPree AST

**Comment by developit** [comment]
The medium-term fix would be to allow using Babel with Microbundle, triggered by the existence of a `.babelrc`.

**Comment by Andarist** [comment]
@developit I've had a WIP [here](https://github.com/developit/microbundle/pull/39). Should we revive this PR until we switch to babel entirely?

**Comment by chrstntdd** [comment]
Maybe not the right place for this, but I have a typescript project using `0.7.0` which I have upgraded to `0.8.3`. Before the upgrade, targeting ES5 would inject the `__assign` helper from typescript, but now that helper has been removed from the output bundle. Normally I would welcome this, but since the output is no longer valid ES5 I can't make the upgrade.

**Comment by marvinhagemeister** [comment]
Just tried it out with `0.9.0` and I can't reproduce this issue anymore with the code from the first post.
