### ISSUE TITLE
`--cwd` and `--tsconfig`

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [developit/microbundle#939]
Is it expected that `tsconfig` resolves against the calling directory even when `--cwd` is specified? I have a use case where I have a browser lib and a node lib in the same repo that have distinct `tsconfig.json` files. Currently I have to specify the full path to make `tsconfig.json` discovery work, that is `--cwd a/b/c --tsconfig a/b/c/tsconfig.json` instead of just `--cwd a/b/c --tsconfig tsconfig.json` or just `--cwd a/b/c`. Is there some other configuration that I do not know about that would make this more intuitive?

**Comment by rschristian** [comment]
It's not intentional, no. Just an oversight!

If you're willing to implement this (I can otherwise take a look over the next couple days probably), it should be pretty simple (I believe. TS can quickly become a rabbit hole, so hopefully I'm not too naive for hoping this is simple).

[rpt2](https://github.com/ezolenko/rollup-plugin-typescript2) resolves a `tsconfig.json` against the current working dir. So what should happen is that when `cwd != '.'` and `--tsconfig` is `undefined` (default val), we should try to resolve a ``​`${cwd}/tsconfig.json`​``. If it exists, set `options.tsconfig` so it can be passed into the plugin here:

https://github.com/developit/microbundle/blob/fb0a43780a7462f4876955c3412638e51a7adb97/src/index.js#L544

**Comment by make-github-pseudonymous-again** [comment]
Thanks @rschristian !

**Comment by rschristian** [comment]
Np, not sure when it'll make sense to cut a release but hopefully something like [`patch-package`](https://npm.im/patch-package) could hold you over in the mean time.
