### ISSUE TITLE
BigInt exponentiation `2n ** 63n` transpiled to `Math.pow(2n, 63n)` in CommonJS output

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [developit/microbundle#953]
Expected? It is broken on Node v17.9.0.

**Comment by rschristian** [comment]
Yes, this is correct. Everything but the `modern` output is ES5 while the exponentiation operator is ES2016.

If you'd like to alter the targets you can do so using a `"browserslist"` entry in your `package.json`:

```json
{
  "browserslist": [
    "node >= 7"
  ]
}
```

If you're only after Node compat, then this config will work. This operator has been supported since Node v7 ([source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Exponentiation#browser_compatibility))

**Comment by make-github-pseudonymous-again** [comment]
Thanks @rschristian. Is there a way to fix this with `--taget web`? I was only giving out node version because that's what I use to run microbundle.

**Comment by rschristian** [comment]
Yep, certainly can! Just edit the browserslist:

```
// package.json
{
  "browserslist": [
    "last 5 years"
  ]
}
```

Should do the trick.

**Comment by rschristian** [comment]
Closing this out as it's hopefully been answered. Let me know if you're still having issues and I can reopen.
