### ISSUE TITLE
is Hashing filename supported ?

### ISSUE THREAD

**Issue by AdhisivamS** [developit/microbundle#965]

**Comment by rschristian** [comment]
Hashing entry points wouldn't make much sense, as you wouldn't have stable names to add to your `package.json` or request from a CDN. So that's not supported.

Filenames _can_ get a hash under certain circumstances, like dynamically importing another module. Microbundle will output that module as well, with a file name of `<module>.<hash>.js`. This isn't an entry point though, so you wouldn't be directly  using it.

Hope this answered your question
